
const express=require('express'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');
const {User,Product,Store,Order}=require('../db'); const {requireAdmin}=require('../middleware/auth');
const router=express.Router(); const safeUser=u=>{const o=u.toObject?u.toObject():{...u};delete o.password;delete o._id;delete o.__v;return o;};
router.post('/login',async(req,res)=>{try{const e=String(req.body.email||'').trim().toLowerCase(),p=String(req.body.password||'');const u=await User.findOne({email:e,isAdmin:true});if(!u||!await bcrypt.compare(p,u.password))return res.status(401).json({message:'Invalid admin credentials.'});const token=jwt.sign({id:u.id,email:u.email,name:u.name,isAdmin:true},process.env.JWT_SECRET,{expiresIn:'12h'});res.json({message:'Admin login successful',user:safeUser(u),token});}catch(e){console.error(e);res.status(500).json({message:'Unable to login as admin.'})}});
router.use(requireAdmin);
router.get('/stats',async(req,res)=>{const [products,users,totalOrders,pending,delivered,recent]=await Promise.all([Product.countDocuments(),User.countDocuments(),Order.countDocuments(),Order.countDocuments({status:'Order Placed'}),Order.countDocuments({status:'Delivered'}),Order.find().sort({createdAt:-1}).limit(5).lean()]);const revenue=await Order.aggregate([{$match:{paymentStatus:{$in:['paid','pending','refund_requested','refunded']}}},{$group:{_id:null,total:{$sum:'$total'}}}]);res.json({totalProducts:products,totalUsers:users,totalOrders,totalRevenue:revenue[0]?.total||0,pendingOrders:pending,deliveredOrders:delivered,recentOrders:recent});});
router.get('/products',async(req,res)=>res.json(await Product.find().lean()));
router.post('/products',async(req,res)=>res.status(201).json({message:'Product added',product:await Product.create({id:Date.now(),...req.body,createdAt:new Date().toISOString()})}));
router.put('/products/:id',async(req,res)=>{const p=await Product.findOneAndUpdate({id:Number(req.params.id)},{$set:{...req.body,updatedAt:new Date().toISOString()}},{new:true});if(!p)return res.status(404).json({message:'Product not found'});res.json({message:'Product updated',product:p})});
router.delete('/products/:id',async(req,res)=>{const p=await Product.findOneAndDelete({id:Number(req.params.id)});if(!p)return res.status(404).json({message:'Product not found'});res.json({message:'Product deleted',product:p})});
async function store(){return Store.findOne({key:'main'})}
async function arrayCrud(field,req,res,mode){const s=await store();if(!s)return res.status(500).json({message:'Store configuration missing'});if(mode==='get')return res.json(s[field]||[]);if(mode==='post'){const item={id:Date.now(),...req.body,...(field==='banners'||field==='deals'?{active:true}:{})};s[field]=[...(s[field]||[]),item];await s.save();return res.status(201).json({message:`${field.slice(0,-1)} added`,[field.slice(0,-1)]:item});}const id=Number(req.params.id),idx=(s[field]||[]).findIndex(x=>Number(x.id)===id);if(idx<0)return res.status(404).json({message:`${field.slice(0,-1)} not found`});if(mode==='put')s[field][idx]={...s[field][idx],...req.body};else s[field].splice(idx,1);await s.save();return res.json({message:`${field.slice(0,-1)} ${mode==='put'?'updated':'deleted'}`,[field.slice(0,-1)]:mode==='put'?s[field][idx]:null});}
for(const f of ['categories','banners','deals']){router.get('/'+f,(req,res)=>arrayCrud(f,req,res,'get'));router.post('/'+f,(req,res)=>arrayCrud(f,req,res,'post'));router.put('/'+f+'/:id',(req,res)=>arrayCrud(f,req,res,'put'));router.delete('/'+f+'/:id',(req,res)=>arrayCrud(f,req,res,'delete'));}
router.get('/users',async(req,res)=>res.json((await User.find()).map(safeUser)));
router.delete('/users/:id',async(req,res)=>{const u=await User.findOneAndDelete({id:Number(req.params.id),isAdmin:{$ne:true}});if(!u)return res.status(404).json({message:'User not found or cannot delete admin'});res.json({message:'User deleted',user:safeUser(u)})});
router.get('/orders',async(req,res)=>res.json(await Order.find().sort({createdAt:-1}).lean()));
router.put('/orders/:id',async(req,res)=>{const o=await Order.findOneAndUpdate({id:Number(req.params.id)},{$set:{...req.body,updatedAt:new Date().toISOString()}},{new:true});if(!o)return res.status(404).json({message:'Order not found'});if(global.io)global.io.emit('order-updated',o.toObject());res.json({message:'Order updated',order:o})});
router.get('/settings',async(req,res)=>{const s=await store();res.json(s?.settings||{})});
router.put('/settings',async(req,res)=>{const s=await store();s.settings={...(s.settings||{}),...req.body,updatedAt:new Date().toISOString()};await s.save();res.json({message:'Settings updated',settings:s.settings})});
module.exports=router;
